# Generated by Django 5.1.6 on 2025-04-13 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notify_by_email_on_status_change',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='notify_in_app_on_status_change',
            field=models.BooleanField(default=True),
        ),
    ]
