# Generated by Django 5.1.6 on 2025-03-26 04:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Colloquium",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("date", models.DateField()),
                ("description", models.TextField()),
                ("video_link", models.URLField(blank=True, null=True)),
                (
                    "presentation_file",
                    models.FileField(
                        blank=True, null=True, upload_to="colloquium_presentations/"
                    ),
                ),
                (
                    "presenter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ResearchProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("abstract", models.TextField()),
                ("submission_date", models.DateTimeField(auto_now_add=True)),
                (
                    "approval_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("github_link", models.URLField(blank=True, null=True)),
                (
                    "project_sponsor",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "poster_image",
                    models.ImageField(blank=True, null=True, upload_to="posters/"),
                ),
                ("video_link", models.URLField(blank=True, null=True)),
                (
                    "presentation_file",
                    models.FileField(blank=True, null=True, upload_to="presentations/"),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True, null=True, upload_to="research_papers/"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="research_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "collaborators",
                    models.ManyToManyField(
                        blank=True,
                        related_name="collaborations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "faculty_advisor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="advised_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
