# Generated by Django 5.1.6 on 2025-04-13 19:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Colloquium",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("date", models.DateField()),
                ("description", models.TextField()),
                ("video_link", models.URLField(blank=True, null=True)),
                (
                    "presentation_file",
                    models.FileField(
                        blank=True, null=True, upload_to="colloquium_presentations/"
                    ),
                ),
                (
                    "presenter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ResearchProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("abstract", models.TextField()),
                ("student_author_name", models.CharField(blank=True, max_length=255)),
                (
                    "collaborator_names",
                    models.TextField(
                        blank=True,
                        help_text="Enter collaborator names, separated by commas",
                    ),
                ),
                ("submission_date", models.DateTimeField(auto_now_add=True)),
                ("date_presented", models.DateField(blank=True, null=True)),
                (
                    "approval_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("needs_revision", "Needs Revision"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                ("admin_feedback", models.TextField(blank=True, null=True)),
                ("github_link", models.URLField(blank=True, null=True)),
                (
                    "project_sponsor",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "poster_image",
                    models.ImageField(blank=True, null=True, upload_to="posters/"),
                ),
                ("video_link", models.URLField(blank=True, null=True)),
                (
                    "presentation_file",
                    models.FileField(blank=True, null=True, upload_to="presentations/"),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True, null=True, upload_to="research_papers/"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="research_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "faculty_advisor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="advised_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "status_from",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pending", "Pending Approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("needs_revision", "Needs Revision"),
                        ],
                        max_length=15,
                        null=True,
                    ),
                ),
                (
                    "status_to",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("needs_revision", "Needs Revision"),
                        ],
                        max_length=15,
                    ),
                ),
                ("comment", models.TextField(blank=True, null=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="research.researchproject",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Status Histories",
                "ordering": ["-timestamp"],
            },
        ),
    ]
