# Generated by Django 5.1.6 on 2025-03-26 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("research", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="researchproject",
            name="collaborators",
        ),
        migrations.AddField(
            model_name="researchproject",
            name="collaborator_names",
            field=models.TextField(
                blank=True, help_text="Enter collaborator names, separated by commas"
            ),
        ),
        migrations.AddField(
            model_name="researchproject",
            name="date_presented",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="researchproject",
            name="student_author_name",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
