# Generated by Django 5.1.6 on 2025-04-27 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0004_projectimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchproject',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='PDF of the research paper (max 10MB)', null=True, upload_to='research_papers/', verbose_name='Research Paper (PDF)'),
        ),
        migrations.AlterField(
            model_name='researchproject',
            name='poster_image',
            field=models.FileField(blank=True, help_text='Poster image or PDF (max 5MB, allowed: jpg, png, pdf)', null=True, upload_to='posters/', verbose_name='Research Poster'),
        ),
        migrations.AlterField(
            model_name='researchproject',
            name='presentation_file',
            field=models.FileField(blank=True, help_text='Presentation slides (PDF, PPT, PPTX, max 10MB)', null=True, upload_to='presentations/', verbose_name='Presentation Slides'),
        ),
    ]
