# Generated by Django 5.1.6 on 2025-04-13 09:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("research", "0003_researchproject_admin_feedback_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="colloquium",
            name="presentation_file",
            field=models.FileField(
                blank=True, null=True, upload_to="colloquium_presentations/"
            ),
        ),
        migrations.AddField(
            model_name="researchproject",
            name="pdf_file",
            field=models.FileField(blank=True, null=True, upload_to="research_papers/"),
        ),
        migrations.AddField(
            model_name="researchproject",
            name="poster_image",
            field=models.ImageField(blank=True, null=True, upload_to="posters/"),
        ),
        migrations.AddField(
            model_name="researchproject",
            name="presentation_file",
            field=models.FileField(blank=True, null=True, upload_to="presentations/"),
        ),
        migrations.AlterField(
            model_name="projectfile",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="projectfile",
            name="file_type",
            field=models.CharField(
                choices=[
                    ("paper", "Research Paper"),
                    ("poster", "Poster"),
                    ("presentation", "Presentation Slides"),
                    ("image", "Image"),
                    ("code", "Source Code"),
                    ("data", "Dataset"),
                    ("latex", "LaTeX Source"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=50,
            ),
        ),
    ]
