name: Django CI

on:
  push:
    branches: [ "main" ] # Adjust if your main branch is different
  pull_request:
    branches: [ "main" ] # Adjust if your main branch is different

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.11"] # Use the Python version your project uses

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r research_showcase/requirements.txt
    - name: Run Tests
      run: |
        python research_showcase/manage.py test 